# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
