# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0002_dailylog_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailylog',
            old_name='amount',
            new_name='quantity',
        ),
    ]
