# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0004_auto_20171015_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='work_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
