# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0005_auto_20171015_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='is_freecharge',
            field=models.BooleanField(default=False),
        ),
    ]
