# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailywork', '0006_dailylog_is_freecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='invalid',
            field=models.BooleanField(default=False, verbose_name='項目作廢'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='is_freecharge',
            field=models.BooleanField(default=False, verbose_name='免費項目'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='payrequest',
            field=models.BooleanField(default=False, verbose_name='已請款'),
        ),
    ]
