# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-21 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
