# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bill_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='項目作廢'),
        ),
    ]
