# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20171031_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
