# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20171031_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paied',
            field=models.BooleanField(default=False),
        ),
    ]
