# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-30 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20171015_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='faxno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='傳真'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='invalid',
            field=models.BooleanField(default=False, verbose_name='停用'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(max_length=36, verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='unikey',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='統一編號'),
        ),
    ]
