# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20171031_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='unikey',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='統一編號'),
        ),
    ]
